credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "PTN-jenkins-agent-credential"
          id: "PTN-jenkins-agent-credential"
          privateKeySource:
            directEntry:
              #privateKey: "${readFile:/var/secrets/jenkins_ed25519}"
              privateKey: "${sec_jenkins_ed25519}"
          scope: SYSTEM
          username: ${JENKINS_ADMIN_ID}
      - usernamePassword:
          id: "Soph_Github_repo_readonly"
          password: "${sec_soph_repo_read_pkey}"
          scope: GLOBAL
          username: "sophoah"
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_ID}"
        - "Overall/Read:authenticated"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  remotingSecurity:
    enabled: true
  labelAtoms:
    - name: "jenkins-ptn-agent"
    - name: "PTN-Admin"
    - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodes:
  - permanent:
      labelString: "PTN-Admin"
      launcher:
        ssh:
          credentialsId: "PTN-jenkins-agent-credential"
          host: "jenkins.pops.one"
          port: 22
          sshHostKeyVerificationStrategy: "knownHostsFileKeyVerificationStrategy"
      name: "PTN-Admin"
      nodeDescription: "PTN-Admin"
      numExecutors: 1
      remoteFS: "/home/pops/jenkins/popsworkspace"
      retentionStrategy: "always"
  numExecutors: 2
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: ${JENKINS_URL}

jobs:
  - script: >
      pipelineJob('PTN-Upgrade') {
          definition {
              cpsScm {
                  scriptPath 'jobs/Upgrade-PTN/Jenkinsfile'
                  scm {
                    git {
                        remote { 
                          url 'https://github.com/sophoah/jenkins.git' 
                          credentials("Soph_Github_repo_readonly")
                        }
                        branch '*/master'
                        extensions {}
                    }
                    lightweight()
                  }
              }
          }
      }